version: 2

core_defaults: &core_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/buildpack-deps:jessie'

node_defaults: &node_defaults
    working_directory: '~/project'
    docker:
        - image: 'circleci/node:10.4'

deploy_defaults: &deploy_defaults
    working_directory: '~/project'
    docker:
        - image: 'qldockerdtr.rockfin.com/circleci/hal-integration:hal-publisher'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

workflows:

    version: 2

    pipeline:
        jobs:
            - fetch_code
            - install_node_dependencies:
                requires: [ fetch_code ]
            - build_site:
                requires: [ install_node_dependencies ]
            - publish_build:
                requires: [ build_site ]
                filters:
                    branches: { only: ['master'] }
            - deploy_site:
                requires: [ publish_build ]

jobs:
    fetch_code:
        <<: *core_defaults
        steps:
            - checkout
            - *persist_workspace

    install_node_dependencies:
        <<: *node_defaults
        steps:
            - *attach_workspace

            - restore_cache:
                keys: [ 'v1-yarn-deps-{{ checksum "yarn.lock" }}', 'v1-yarn-deps' ]

            - run: 'yarn install'

            - save_cache:
                key: 'v1-yarn-deps-{{ checksum "yarn.lock" }}'
                paths: [ 'node_modules' ]

            - *persist_workspace

    build_site:
        <<: *node_defaults
        steps:
            - *attach_workspace
            - run: 'yarn build'
            - run:
                name: 'Clean up built website'
                command: |
                    mkdir build
                    cp -R dist              build/dist
                    cp -R surveys           build/surveys

                    cp index.html           build/
                    cp error.html           build/
                    cp surveys.json         build/
                    cp sample-survey.json   build/
                    cp survey-schema.json   build/
            - persist_to_workspace:
                root: '.'
                paths: [ 'build' ]

    publish_build:
        <<: *deploy_defaults
        environment:
            - HAL_APP_ID: '671'
            # HAL_API_TOKEN
        steps:
            - *attach_workspace
            - run: 'cd build && pack-build-to-zip'
            - store_artifacts: { path: '~/build' }
            - run: 'publish-build-to-hal'
            - persist_to_workspace:
                root: '.'
                paths: [ '.hal_build_id' ]

    deploy_site:
        <<: *deploy_defaults
        environment:
            - HAL_TARGETS: '3352'
            # HAL_API_TOKEN
        steps:
            - *attach_workspace
            - run: 'deploy-to-hal'
